### ISSUE TITLE
can't connect impala,and the log of impala server show:invalid sasl status

### ISSUE THREAD

**Issue by sugerdear** [Automattic/php-thrift-sql#11]
i try connect the impala,but is error:
client error:
PHP Fatal error:  Uncaught exception 'Thrift\Exception\TTransportException' with message 'TSocket read 0 bytes' in phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Thrift/Transport/TSocket.php:269
Stack trace:
#0 phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Thrift/Transport/TTransport.php(74): Thrift\Transport\TSocket->read(4)
#1 phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Thrift/Protocol/TBinaryProtocol.php(305): Thrift\Transport\TTransport->readAll(4)
#2 phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Thrift/Protocol/TBinaryProtocol.php(197): Thrift\Protocol\TBinaryProtocol->readI32(NULL)
#3 phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Packages/Beeswax/BeeswaxService.php(160): Thrift\Protocol\TBinaryProtocol->readMessageBegin(NULL, 0, 0)
#4 phar:///home/map/rd/liuxiaochun/php-thrift-sql-master/ThriftSQL.phar/Packages/Beeswax/BeeswaxService.php(129): ThriftSQL\BeeswaxServiceClient->recv_query()

server error:
 TThreadPoolServer: TServerTransport died on accept: invalid sasl status

**Comment by pbatchu-fb** [comment]
Did you solve this issue? i am facing similar error. Does this error indicate client is trying to connect to ssl session?

**Comment by xyu** [comment]
Impala does not support SASL connections over Thrift so for unauthenticated connections we use plain connections for Impala and only implement SASL for unsecured Hive connections. This library does not support SSL'ed connections currently (see issue #28) however with PR #33 we will support sending usernames with Impala queries for tracking over an unsecured (not kerborized connection) so that queries can be tagged with usernames.

**Comment by xyu** [comment]
I'm closing now that #33 has been merged with the option to send usernames with PLAIN connections to Impala.
