### ISSUE TITLE
Required field 'client_protocol' unset error

### ISSUE THREAD

**Issue by zoltan-fedor** [Automattic/php-thrift-sql#7]
Hey,
I run the example, but receiving "Required field 'client_protocol' unset error" error.

> require_once **DIR** .'/../../libraries/php-thrift-sql/src/autoload.php';  
> 
> // Try out a Hive query  
> $hive = new \ThriftSQL\Hive( 'xxx.com', 10000, 'my_user', my_password' );  
> $hiveTables = $hive  
>  ->connect()  
>  ->queryAndFetchAll( 'SHOW TABLES' );  
> print_r( $hiveTables );  
> 
> // Don't forget to clear the client and close socket.  
> $hive->disconnect();  

Returned:

> PHP Fatal error:  Uncaught exception 'Thrift\Exception\TApplicationException' with message 'Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, username:biapp, password:5Pusecup)' in /biapps/hadoop/libraries/php-thrift-sql/src/Packages/TCLIService/TCLIService.php:164  
> Stack trace:  
> # 0 /biapps/hadoop/libraries/php-thrift-sql/src/Packages/TCLIService/TCLIService.php(131): ThriftSQL\TCLIServiceClient->recv_OpenSession()
> # 1 /biapps/hadoop/libraries/php-thrift-sql/src/ThriftSQL/Hive.php(70): ThriftSQL\TCLIServiceClient->OpenSession(Object(ThriftSQL\TOpenSessionReq))
> # 2 /biapps/hadoop/importers/hive_test/test.php(8): ThriftSQL\Hive->connect()
> # 3 {main}
> 
>   thrown in /biapps/hadoop/libraries/php-thrift-sql/src/Packages/TCLIService/TCLIService.php on line 164

**Comment by zoltan-fedor** [comment]
My guess that it is probably due to different version of hive-jdbc, I'm trying to connect to 0.12

**Comment by zoltan-fedor** [comment]
Here is the Hive bug: https://issues.apache.org/jira/browse/HIVE-6050
Due to this Hive clients are not backward compatible, so a newer Hive client cannot connect to an older Hive server.

**Comment by zoltan-fedor** [comment]
Is there any way to use this library with a Hive 0.12 client, so it can connect to Hive 0.12 server with SASL?

**Comment by xyu** [comment]
I suppose an older version of `TCLIService.php` can be compiled by thrift and swapped in a separate branch. (I'm not sure if there's a clean way to support both in one PHAR.) However I don't have a old hive server running so I can't really test that.

**Comment by liupu1106** [comment]
I am using hive-jdbc 2.1.1 and hive version 2.1.1 and it is not working.
Need Help

**Comment by lenchvolodymyr** [comment]
I've faced such problem when tried to connect to Hive with version lower than API. This looks like API has out of date (https://github.com/Automattic/php-thrift-sql/blob/master/src/Packages/TCLIService/Types.php#L4458) because Hive is supporting the protocol of 10th version now (https://github.com/apache/hive/blob/master/service-rpc/src/gen/thrift/gen-php/Types.php#L29)

**Comment by xyu** [comment]
This library is built against a specific version of Hive and Impala because that's the only environment that I currently have to test with. 😞

With the changes in #33 it will be much easier to rebuild the lib against other versions of Hive and Impala because the build process has been abstracted out into a `Makefile` and versions that are built upon are simply git submodules that point to the published repos on GitHub. Having said that because I still don't have environments with other versions of Hive and Impala I have no way to test it. So it might be better if people who needs other versions to branch, compile, and test on an as needed basis.

**Comment by xyu** [comment]
I'm closing this issue now that #33 has been merged. If anyone has a combination of versions for Hive or Impala that does not work it's possible to change the versions via submodule checkout and rebuild the lib now. If anyone wants to take ownership of updating the lib for different versions we can open new issues / branches in the future.
